research_elections_task:
  description: >
    Conduct a thorough research about {candidate} previous elections results
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {candidate} previous elections results
  agent: researcher

research_corruption_task:
  description: >
    Conduct a thorough research about {candidate} corruption and criminal activity
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {candidate} corruption and criminal activity
  agent: corruption_journalist

research_good_projects_task:
  description: >
    Conduct a thorough research about {candidate} honorable participation in good projects
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {candidate} honorable participation in good projects
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
